### ISSUE TITLE
Chrome无法导入？

### ISSUE THREAD

**Issue by ninsiu-com** [dark-kingA/superSearchPlus#10]
直接提示版本2不能使用host_permissions，修改为版本3，直接提示backgroud.scripts不行？这。。。

**Comment by dark-kingA** [comment]
<img width="834" alt="image" src="https://github.com/dark-kingA/superSearchPlus/assets/102812179/ff006de0-6ae3-4ca1-887a-ab8d1930fa41">
提示确实会提示 但是不会影响使用

**Comment by dark-kingA** [comment]
已解决
