### ISSUE TITLE
关于superSearchPlus使用问题

### ISSUE THREAD

**Issue by zornsoon** [dark-kingA/superSearchPlus#16]
大佬好，就是在使用“资产测绘查询“的时候，自动判断当前是域名还是ip，然后语法设定为ip="x.x.x.x"，domain="x.x.x.x"，不然就是这鸭子使用不同的资产测绘平台，都要自己设置一遍语法，有些麻烦。
![image](https://github.com/dark-kingA/superSearchPlus/assets/61613298/8c857ac1-68b8-4903-a2e5-83fb98b313f5)

**Comment by dark-kingA** [comment]
fofa、零零信安 可以满足 其他的需手动，因为自动查询会扣除积分。

**Comment by zornsoon** [comment]
能不能添加一个选项，就是开启后，所有平台自动会进行查询，并且根据当前是否是ip，还是域名，设置ip="x.x.x.x"、domain="x.x.x.x"

**Comment by zornsoon** [comment]
大佬，能不能添加一个选项，就是开启后，所有平台自动会进行查询，并且根据当前是否是ip，还是域名，设置ip="x.x.x.x"、domain="x.x.x.x"
