### ISSUE TITLE
 请问下chrome版本的链接可以发下么？在goole chrome store找了好久了，都没发现有发行版本。

### ISSUE THREAD

**Issue by ruchid123123** [dark-kingA/superSearchPlus#22]
请问下chrome版本的链接可以发下么？在goole chrome store找了好久了，都没发现有发行版本。

**Comment by dark-kingA** [comment]
目前没有发布在chrome市场 请仔细阅读 文档

**Comment by ruchid123123** [comment]
> 目前尚未在chrome市场发布，请仔细阅读文档

手动安装好了，很好用，期待早日上架chrome商店！谢谢师傅的插件！
