### ISSUE TITLE
hunter报错，起始时间参数错误

### ISSUE THREAD

**Issue by twsec-pro** [dark-kingA/superSearchPlus#4]
![image](https://user-images.githubusercontent.com/58679784/215682517-d8e2df2c-8e34-48ac-b192-d09323c6fdf4.png)

**Comment by twsec-pro** [comment]
soall报错，
![image](https://user-images.githubusercontent.com/58679784/215682776-2a4e58e2-dcf1-4360-8596-593e1b4cda5f.png)

**Comment by dark-kingA** [comment]
hunter已经修改了 
https://soall.org/ 已关站了

**Comment by dark-kingA** [comment]
关闭
