### ISSUE TITLE
建议增加关闭插件功能

### ISSUE THREAD

**Issue by 0nion1** [dark-kingA/superSearchPlus#6]
师傅，建议增加一个自定义ui的功能，部分插件可能用不到，
1、支持关闭插件以免占用浏览器资源。
2、综合查询这个功能查询网站时候可以保存在缓存，一个网站综合查询网站的备案时候很多时候显示不出来。

**Comment by dark-kingA** [comment]
1.插件不点击不会开启查询 
2.这个貌似是慢 如果上了科学上网 可能就g了
有问题在公众号在私信我吧

**Comment by dark-kingA** [comment]
1.插件不点击不会开启查询 
2.这个貌似是慢 如果上了科学上网 可能就g了
有问题在公众号在私信我吧

**Comment by dark-kingA** [comment]
关闭
