### ISSUE TITLE
自动摧毁插件

### ISSUE THREAD

**Issue by A7cc** [dark-kingA/superSearchPlus#9]
该插件在安装到谷歌浏览器后，使用一次后会自动摧毁！这是什么原因？

**Comment by A7cc** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dark-kingA/superSearchPlus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月20日(星期四) 晚上6:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dark-kingA/superSearchPlus] 自动摧毁插件 (Issue #9)





 
截图发我

**Comment by A7cc** [comment]
![20230721151531](https://github.com/dark-kingA/superSearchPlus/assets/47489441/665aabc3-64d1-4435-afd7-80a13e494003)
![20230721152319](https://github.com/dark-kingA/superSearchPlus/assets/47489441/5956850c-c412-46c6-8209-3edca083cd89)

**Comment by dark-kingA** [comment]
你关注下 红蓝攻防实验室公众号 里面有个加我的地方 加我下

**Comment by dark-kingA** [comment]
已解决
